-- Execute este script no Supabase SQL Editor.
-- Ele cria/ajusta estrutura, view, funcao RPC e RLS para o projeto.

create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) >= 2),
  description text,
  image_url text,
  buy_url text,
  price_value numeric(12,2),
  is_active boolean not null default true,
  display_order integer not null default 0 check (display_order >= 0),
  qty_total integer not null check (qty_total > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gifts
  add column if not exists created_at timestamptz not null default now();

alter table public.gifts
  add column if not exists updated_at timestamptz not null default now();

alter table public.gifts
  add column if not exists price_value numeric(12,2);

alter table public.gifts
  add column if not exists is_active boolean not null default true;

alter table public.gifts
  add column if not exists display_order integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'gifts_display_order_nonnegative'
      and conrelid = 'public.gifts'::regclass
  ) then
    alter table public.gifts
      add constraint gifts_display_order_nonnegative
      check (display_order >= 0);
  end if;
end $$;

create table if not exists public.gift_classifications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) >= 2),
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id smallint primary key check (id = 1),
  instructions_html text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.site_content (id, instructions_html)
values (1, '')
on conflict (id) do nothing;

create unique index if not exists ux_gift_classifications_name_lower
  on public.gift_classifications(lower(name));

alter table public.gift_classifications
  add column if not exists display_order integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'gift_classifications_display_order_nonnegative'
      and conrelid = 'public.gift_classifications'::regclass
  ) then
    alter table public.gift_classifications
      add constraint gift_classifications_display_order_nonnegative
      check (display_order >= 0);
  end if;
end $$;

alter table public.gifts
  add column if not exists classification_id bigint references public.gift_classifications(id) on delete set null;

create index if not exists idx_gifts_classification_id
  on public.gifts(classification_id);

create index if not exists idx_gifts_is_active
  on public.gifts(is_active);

create index if not exists idx_gift_classifications_order
  on public.gift_classifications(display_order, name, id);

create index if not exists idx_gifts_classification_order
  on public.gifts(classification_id, display_order, id);

create table if not exists public.gift_reservations (
  id bigint generated by default as identity primary key,
  gift_id bigint not null references public.gifts(id) on delete cascade,
  reserved_by text not null check (char_length(trim(reserved_by)) >= 3),
  qty integer not null check (qty > 0),
  reserved_at timestamptz not null default now()
);

create index if not exists idx_gift_reservations_gift_id
  on public.gift_reservations(gift_id);

create index if not exists idx_gift_reservations_reserved_at
  on public.gift_reservations(reserved_at desc);

-- Bloco defensivo para execucao parcial do script
create table if not exists public.gift_classifications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) >= 2),
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now()
);

alter table public.gifts
  add column if not exists classification_id bigint references public.gift_classifications(id) on delete set null;

drop view if exists public.gifts_view;

create view public.gifts_view as
select
  g.id,
  g.title,
  g.description,
  g.image_url,
  g.buy_url,
  g.price_value,
  g.is_active,
  g.display_order,
  g.classification_id,
  c.display_order as classification_display_order,
  c.name as classification_name,
  g.qty_total,
  coalesce(sum(r.qty), 0)::integer as qty_reserved,
  greatest(g.qty_total - coalesce(sum(r.qty), 0), 0)::integer as qty_available
from public.gifts g
left join public.gift_classifications c on c.id = g.classification_id
left join public.gift_reservations r on r.gift_id = g.id
group by g.id, c.id, c.name, c.display_order;

create table if not exists public.admin_emails (
  email text primary key check (position('@' in email) > 1),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_emails a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_gift_title()
returns trigger
language plpgsql
as $$
begin
  new.title = upper(trim(coalesce(new.title, '')));
  return new;
end;
$$;

drop trigger if exists trg_gifts_updated_at on public.gifts;
create trigger trg_gifts_updated_at
before update on public.gifts
for each row
execute function public.set_updated_at();

drop trigger if exists trg_gifts_normalize_title on public.gifts;
create trigger trg_gifts_normalize_title
before insert or update on public.gifts
for each row
execute function public.normalize_gift_title();

update public.gifts
set title = upper(trim(title))
where title is not null
  and title <> upper(trim(title));

create or replace function public.reserve_gift(
  p_gift_id bigint,
  p_name text,
  p_qty integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(coalesce(p_name, ''));
  v_qty integer := coalesce(p_qty, 0);
  v_total integer;
  v_is_active boolean;
  v_reserved integer;
begin
  if v_name !~ '\S+\s+\S+' then
    raise exception 'INVALID_NAME';
  end if;

  if v_qty <= 0 then
    raise exception 'INVALID_QTY';
  end if;

  select g.qty_total, g.is_active
    into v_total, v_is_active
  from public.gifts g
  where g.id = p_gift_id
  for update;

  if not found then
    raise exception 'GIFT_NOT_FOUND';
  end if;

  if coalesce(v_is_active, true) = false then
    raise exception 'GIFT_INACTIVE';
  end if;

  select coalesce(sum(r.qty), 0)::integer
    into v_reserved
  from public.gift_reservations r
  where r.gift_id = p_gift_id;

  if (v_total - v_reserved) < v_qty then
    raise exception 'NOT_ENOUGH_QTY';
  end if;

  insert into public.gift_reservations (gift_id, reserved_by, qty)
  values (p_gift_id, v_name, v_qty);

  return jsonb_build_object('ok', true);
end;
$$;

alter table public.gifts enable row level security;
alter table public.gift_classifications enable row level security;
alter table public.gift_reservations enable row level security;
alter table public.site_content enable row level security;
alter table public.admin_emails disable row level security;

drop policy if exists gifts_public_select on public.gifts;
create policy gifts_public_select
on public.gifts
for select
to anon, authenticated
using (true);

drop policy if exists gifts_admin_write on public.gifts;
create policy gifts_admin_write
on public.gifts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists classifications_public_select on public.gift_classifications;
create policy classifications_public_select
on public.gift_classifications
for select
to anon, authenticated
using (true);

drop policy if exists classifications_admin_write on public.gift_classifications;
create policy classifications_admin_write
on public.gift_classifications
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists site_content_public_select on public.site_content;
create policy site_content_public_select
on public.site_content
for select
to anon, authenticated
using (true);

drop policy if exists site_content_admin_write on public.site_content;
create policy site_content_admin_write
on public.site_content
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists reservations_public_select on public.gift_reservations;
create policy reservations_public_select
on public.gift_reservations
for select
to anon, authenticated
using (true);

drop policy if exists reservations_admin_delete on public.gift_reservations;
create policy reservations_admin_delete
on public.gift_reservations
for delete
to authenticated
using (public.is_admin());

revoke all on public.admin_emails from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.gifts_view to anon, authenticated;
grant select on public.gifts to anon, authenticated;
grant select on public.gift_classifications to anon, authenticated;
grant select on public.gift_reservations to anon, authenticated;
grant select on public.site_content to anon, authenticated;
grant insert, update on public.gifts to authenticated;
grant insert, update, delete on public.gift_classifications to authenticated;
grant delete on public.gift_reservations to authenticated;
grant insert, update on public.site_content to authenticated;
grant execute on function public.reserve_gift(bigint, text, integer) to anon, authenticated;
grant execute on function public.is_admin() to authenticated;

do $$
begin
  if to_regclass('public.gifts_id_seq') is not null then
    execute 'grant usage, select on sequence public.gifts_id_seq to authenticated';
  end if;
  if to_regclass('public.gift_reservations_id_seq') is not null then
    execute 'grant usage, select on sequence public.gift_reservations_id_seq to authenticated';
  end if;
  if to_regclass('public.gift_classifications_id_seq') is not null then
    execute 'grant usage, select on sequence public.gift_classifications_id_seq to authenticated';
  end if;
end $$;

-- Depois de criar seu usuario admin no Supabase Auth:
-- insert into public.admin_emails(email) values ('seu-email@dominio.com') on conflict do nothing;
